"""baseline schema (squash of history through q5r6s7t8u9v0)

Revision ID: 0001_baseline
Revises:
Create Date: 2026-07-27

WHY THIS EXISTS
---------------
The pre-squash migration chain (46 revisions, 06f355945bf5 .. q5r6s7t8u9v0)
NEVER created ~50 of the 58 tables via a migration. They were bootstrapped on
prod by SQLAlchemy `Base.metadata.create_all()`, and every later migration just
layered add_column / create_index / data-UPDATE ops on top of that implicit
baseline. That worked on prod but meant a from-scratch `alembic upgrade head`
(exactly what CI runs) crashed at the first migration that touched a
non-existent table (c3d4e5f6a7b8 indexing `training_claims`).

This revision squashes the entire history into one baseline generated from the
current models (Base.metadata), so a clean DB can reach head and `alembic check`
reports no drift. Prod (already at q5r6s7t8u9v0, schema == models) was stamped to
0001_baseline at deploy time so it does not attempt to recreate existing tables.
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '0001_baseline'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('value_type', sa.String(length=8), nullable=False),
    sa.Column('label', sa.String(length=128), nullable=True),
    sa.Column('category', sa.String(length=32), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('certifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('criteria', sa.Text(), nullable=True),
    sa.Column('resources', sa.Text(), nullable=True),
    sa.Column('icon', sa.String(length=8), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('elections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('phase', sa.String(length=16), nullable=False),
    sa.Column('nominations_open', sa.DateTime(), nullable=True),
    sa.Column('nominations_close', sa.DateTime(), nullable=True),
    sa.Column('voting_open', sa.DateTime(), nullable=True),
    sa.Column('voting_close', sa.DateTime(), nullable=True),
    sa.Column('quorum_pct', sa.Integer(), nullable=False),
    sa.Column('eligible_count', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('runoff_of', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['runoff_of'], ['elections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('event_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('label', sa.String(length=48), nullable=False),
    sa.Column('icon', sa.String(length=16), nullable=False),
    sa.Column('rsvp_default', sa.Boolean(), nullable=False),
    sa.Column('warno_lead_days', sa.Integer(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('library_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('icon', sa.String(length=16), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('library_document',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=16), nullable=False),
    sa.Column('pub_number', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('pub_date', sa.String(length=32), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('stored_path', sa.String(length=512), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=False),
    sa.Column('mime_type', sa.String(length=128), nullable=False),
    sa.Column('uploaded_by', sa.String(length=64), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('member_statuses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('label', sa.String(length=32), nullable=False),
    sa.Column('color', sa.String(length=16), nullable=False),
    sa.Column('lifecycle', sa.String(length=16), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('member_weapons_qual',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('qualified_on', sa.Date(), nullable=True),
    sa.Column('recorded_by', sa.String(length=64), nullable=False),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_member_weapons_qual_event_id'), 'member_weapons_qual', ['event_id'], unique=False)
    op.create_index(op.f('ix_member_weapons_qual_member_id'), 'member_weapons_qual', ['member_id'], unique=False)
    op.create_table('members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nc_username', sa.String(length=64), nullable=False),
    sa.Column('first_name', sa.String(length=64), nullable=False),
    sa.Column('last_name', sa.String(length=64), nullable=False),
    sa.Column('callsign', sa.String(length=32), nullable=True),
    sa.Column('serial_number', sa.String(length=20), nullable=True),
    sa.Column('serial_seq', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('rank_grade', sa.String(length=4), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('team', sa.String(length=32), nullable=True),
    sa.Column('team_locked', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('company', sa.String(length=64), nullable=False),
    sa.Column('leadership_title', sa.Text(), nullable=True),
    sa.Column('primary_billet', sa.Text(), nullable=True),
    sa.Column('secondary_billet', sa.String(length=64), nullable=True),
    sa.Column('join_date', sa.Date(), nullable=True),
    sa.Column('patch_date', sa.Date(), nullable=True),
    sa.Column('separation_date', sa.Date(), nullable=True),
    sa.Column('on_leave', sa.Boolean(), nullable=False),
    sa.Column('leave_start', sa.Date(), nullable=True),
    sa.Column('leave_end', sa.Date(), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('city', sa.String(length=64), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('state', sa.String(length=2), nullable=True),
    sa.Column('zip_code', sa.String(length=10), nullable=True),
    sa.Column('personal_email', sa.String(length=128), nullable=True),
    sa.Column('emergency_contact', sa.String(length=128), nullable=True),
    sa.Column('emergency_phone', sa.String(length=20), nullable=True),
    sa.Column('contact_verified_at', sa.DateTime(), nullable=True),
    sa.Column('ham_callsign', sa.String(length=10), nullable=True),
    sa.Column('ham_license_class', sa.String(length=16), nullable=True),
    sa.Column('gmrs_callsign', sa.String(length=10), nullable=True),
    sa.Column('last_ftx', sa.Date(), nullable=True),
    sa.Column('ftx_count', sa.Integer(), nullable=False),
    sa.Column('is_founder', sa.Boolean(), nullable=False),
    sa.Column('is_hq', sa.Boolean(), nullable=False),
    sa.Column('is_veteran', sa.Boolean(), nullable=False),
    sa.Column('mos', sa.Text(), nullable=True),
    sa.Column('has_ltc', sa.Boolean(), nullable=False),
    sa.Column('app_fee_status', sa.String(length=16), nullable=True),
    sa.Column('app_fee_amount', sa.Float(), nullable=True),
    sa.Column('app_fee_paid_at', sa.DateTime(), nullable=True),
    sa.Column('app_fee_method', sa.String(length=32), nullable=True),
    sa.Column('nda_signed_at', sa.DateTime(), nullable=True),
    sa.Column('nda_ip_address', sa.String(length=255), nullable=True),
    sa.Column('waiver_signed_at', sa.DateTime(), nullable=True),
    sa.Column('waiver_ip_address', sa.String(length=255), nullable=True),
    sa.Column('code_of_conduct_signed_at', sa.DateTime(), nullable=True),
    sa.Column('code_of_conduct_ip_address', sa.String(length=255), nullable=True),
    sa.Column('bylaws_signed_at', sa.DateTime(), nullable=True),
    sa.Column('bylaws_ip_address', sa.String(length=255), nullable=True),
    sa.Column('activity_policy_signed_at', sa.DateTime(), nullable=True),
    sa.Column('activity_policy_ip_address', sa.String(length=255), nullable=True),
    sa.Column('assigned_recruiter', sa.String(length=64), nullable=True),
    sa.Column('recruiter_assigned_at', sa.DateTime(), nullable=True),
    sa.Column('separation_reason', sa.String(length=64), nullable=True),
    sa.Column('separation_notes', sa.Text(), nullable=True),
    sa.Column('separation_initiated_by', sa.String(length=64), nullable=True),
    sa.Column('non_promotable_until', sa.Date(), nullable=True),
    sa.Column('non_promotable_reason', sa.Text(), nullable=True),
    sa.Column('portal_roles', sa.Text(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_members_nc_username'), 'members', ['nc_username'], unique=True)
    op.create_table('nc_rooms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=96), nullable=False),
    sa.Column('meeting_selectable', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('newsletter_section_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('body_html', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('default_order', sa.Integer(), nullable=False),
    sa.Column('preload', sa.Boolean(), nullable=False),
    sa.Column('dynamic_source', sa.String(length=64), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_newsletter_section_templates_key'), 'newsletter_section_templates', ['key'], unique=True)
    op.create_table('newsletters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('subject', sa.String(length=300), nullable=False),
    sa.Column('crest_key', sa.String(length=64), nullable=False),
    sa.Column('body_html', sa.Text(), nullable=False),
    sa.Column('groups_csv', sa.String(length=300), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('recipient_count', sa.Integer(), nullable=False),
    sa.Column('sent_count', sa.Integer(), nullable=False),
    sa.Column('failed_count', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('archive_path', sa.String(length=500), nullable=True),
    sa.Column('created_by', sa.String(length=120), nullable=False),
    sa.Column('created_by_name', sa.String(length=160), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_newsletters_scheduled_at'), 'newsletters', ['scheduled_at'], unique=False)
    op.create_index(op.f('ix_newsletters_status'), 'newsletters', ['status'], unique=False)
    op.create_table('ranks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('grade', sa.String(length=4), nullable=False),
    sa.Column('abbr', sa.String(length=8), nullable=False),
    sa.Column('title', sa.String(length=48), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('insignia', sa.String(length=64), nullable=True),
    sa.Column('nc_group', sa.String(length=48), nullable=True),
    sa.Column('pay_category', sa.String(length=16), nullable=False),
    sa.Column('election_eligible', sa.Boolean(), nullable=False),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('grade')
    )
    op.create_table('recruiters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nc_username', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=128), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('current_load', sa.Integer(), nullable=False),
    sa.Column('max_load', sa.Integer(), nullable=False),
    sa.Column('total_recruited', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nc_username')
    )
    op.create_table('ribbon_catalog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=48), nullable=False),
    sa.Column('name', sa.String(length=96), nullable=False),
    sa.Column('section', sa.String(length=8), nullable=False),
    sa.Column('precedence', sa.Integer(), nullable=False),
    sa.Column('base_points', sa.Integer(), nullable=False),
    sa.Column('device_increment', sa.Integer(), nullable=False),
    sa.Column('max_devices', sa.Integer(), nullable=False),
    sa.Column('image', sa.String(length=160), nullable=True),
    sa.Column('is_auto', sa.Boolean(), nullable=False),
    sa.Column('claimable', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ribbon_catalog_code'), 'ribbon_catalog', ['code'], unique=True)
    op.create_table('shops',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=8), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('short_name', sa.String(length=48), nullable=False),
    sa.Column('icon', sa.String(length=16), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('access_roles', sa.String(length=128), nullable=False),
    sa.Column('has_dashboard', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('designation', sa.String(length=2), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('geo_zone_index', sa.Integer(), nullable=True),
    sa.Column('talk_token', sa.String(length=64), nullable=True),
    sa.Column('color', sa.String(length=16), nullable=True),
    sa.Column('emoji', sa.String(length=16), nullable=True),
    sa.Column('is_hq', sa.Boolean(), nullable=False),
    sa.Column('archived', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('threat_levels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('level', sa.String(length=16), nullable=False),
    sa.Column('set_by', sa.String(length=64), nullable=False),
    sa.Column('set_at', sa.DateTime(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tradoc_blocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('archived', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('tier', sa.String(length=16), server_default='initial', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('number')
    )
    op.create_table('tradoc_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('block', sa.Integer(), nullable=False),
    sa.Column('block_name', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('optional', sa.Boolean(), nullable=False),
    sa.Column('archived', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('doc_type', sa.String(length=16), server_default='none', nullable=False),
    sa.Column('doc_title', sa.String(length=160), nullable=True),
    sa.Column('doc_url', sa.Text(), nullable=True),
    sa.Column('doc_body', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tradoc_tiers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=32), nullable=False),
    sa.Column('label', sa.String(length=96), nullable=False),
    sa.Column('subtitle', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('archived', sa.Boolean(), server_default='false', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('webhook_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('transaction_id', sa.String(length=128), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('outcome', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'transaction_id', name='uq_webhook_provider_txn')
    )
    op.create_table('conduct_violations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('violation_date', sa.Date(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('action_taken', sa.String(length=64), nullable=False),
    sa.Column('duration_days', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('issued_by', sa.String(length=64), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conduct_violations_member_id'), 'conduct_violations', ['member_id'], unique=False)
    op.create_table('document_signatures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('document_type', sa.String(length=32), nullable=False),
    sa.Column('document_version', sa.String(length=16), nullable=False),
    sa.Column('full_name', sa.String(length=128), nullable=False),
    sa.Column('signature_text', sa.String(length=256), nullable=False),
    sa.Column('signed_at', sa.DateTime(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('election_ballots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('election_id', sa.Integer(), nullable=False),
    sa.Column('nominee_id', sa.Integer(), nullable=False),
    sa.Column('cast_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['election_id'], ['elections.id'], ),
    sa.ForeignKeyConstraint(['nominee_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('election_nomination_receipts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('election_id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('nominated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['election_id'], ['elections.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('election_id', 'member_id', name='uq_election_nominator')
    )
    op.create_table('election_nominations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('election_id', sa.Integer(), nullable=False),
    sa.Column('nominee_id', sa.Integer(), nullable=False),
    sa.Column('nominated_at', sa.DateTime(), nullable=False),
    sa.Column('accepted', sa.Boolean(), nullable=True),
    sa.Column('accepted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['election_id'], ['elections.id'], ),
    sa.ForeignKeyConstraint(['nominee_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('election_id', 'nominee_id', name='uq_election_nominee')
    )
    op.create_table('election_voter_roll',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('election_id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('voted_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['election_id'], ['elections.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('election_id', 'member_id', name='uq_election_voter')
    )
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('location', sa.Text(), nullable=True),
    sa.Column('meeting_mode', sa.String(length=16), server_default='physical', nullable=False),
    sa.Column('talk_token', sa.String(length=64), nullable=True),
    sa.Column('instructor_id', sa.Integer(), nullable=True),
    sa.Column('date_start', sa.DateTime(), nullable=False),
    sa.Column('date_end', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('training_block', sa.Integer(), nullable=True),
    sa.Column('training_blocks', sa.String(length=64), nullable=True),
    sa.Column('training_site', sa.String(length=16), nullable=True),
    sa.Column('rally_point', sa.Text(), nullable=True),
    sa.Column('rally_point_time', sa.String(length=8), nullable=True),
    sa.Column('rally_point_set_by', sa.String(length=64), nullable=True),
    sa.Column('rally_point_set_at', sa.DateTime(), nullable=True),
    sa.Column('rally_point_url', sa.Text(), nullable=True),
    sa.Column('fob_callsign', sa.String(length=32), nullable=True),
    sa.Column('freq_convoy_primary', sa.String(length=16), nullable=True),
    sa.Column('freq_convoy_alternate', sa.String(length=16), nullable=True),
    sa.Column('freq_fob_primary', sa.String(length=16), nullable=True),
    sa.Column('freq_fob_alternate', sa.String(length=16), nullable=True),
    sa.Column('opord_situation', sa.Text(), nullable=True),
    sa.Column('opord_mission', sa.Text(), nullable=True),
    sa.Column('opord_execution', sa.Text(), nullable=True),
    sa.Column('opord_admin_logistics', sa.Text(), nullable=True),
    sa.Column('opord_command_signal', sa.Text(), nullable=True),
    sa.Column('rsvp_enabled', sa.Boolean(), nullable=False),
    sa.Column('rsvp_deadline', sa.DateTime(), nullable=True),
    sa.Column('caldav_uid', sa.String(length=255), nullable=True),
    sa.Column('opord_path', sa.Text(), nullable=True),
    sa.Column('warno_scheduled_at', sa.DateTime(), nullable=True),
    sa.Column('warno_issued_at', sa.DateTime(), nullable=True),
    sa.Column('opord_target_date', sa.DateTime(), nullable=True),
    sa.Column('opord_issued_at', sa.DateTime(), nullable=True),
    sa.Column('fragord_issued_at', sa.DateTime(), nullable=True),
    sa.Column('finalized_at', sa.DateTime(), nullable=True),
    sa.Column('finalized_by', sa.String(length=64), nullable=True),
    sa.Column('invite_groups', sa.Text(), nullable=True),
    sa.Column('series_id', sa.String(length=36), nullable=True),
    sa.Column('recurrence_rule', sa.Text(), nullable=True),
    sa.Column('is_series_master', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('aar_commander_intent', sa.Text(), nullable=True),
    sa.Column('aar_mission_summary', sa.Text(), nullable=True),
    sa.Column('aar_published_at', sa.DateTime(), nullable=True),
    sa.Column('aar_published_by', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['instructor_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('caldav_uid')
    )
    op.create_index(op.f('ix_events_series_id'), 'events', ['series_id'], unique=False)
    op.create_table('member_awards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('award_name', sa.String(length=64), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('awarded_by', sa.String(length=64), nullable=True),
    sa.Column('awarded_at', sa.DateTime(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('member_certifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('certification_id', sa.Integer(), nullable=False),
    sa.Column('awarded_by', sa.String(length=64), nullable=True),
    sa.Column('awarded_at', sa.DateTime(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('doc_path', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['certification_id'], ['certifications.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('member_ribbons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('ribbon_code', sa.String(length=48), nullable=False),
    sa.Column('device_count', sa.Integer(), nullable=False),
    sa.Column('awarded_at', sa.DateTime(), nullable=False),
    sa.Column('awarded_by', sa.String(length=64), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=8), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.ForeignKeyConstraint(['ribbon_code'], ['ribbon_catalog.code'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('member_id', 'ribbon_code', name='uq_member_ribbon')
    )
    op.create_index(op.f('ix_member_ribbons_member_id'), 'member_ribbons', ['member_id'], unique=False)
    op.create_index(op.f('ix_member_ribbons_ribbon_code'), 'member_ribbons', ['ribbon_code'], unique=False)
    op.create_table('member_tradoc',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('signed_off_by', sa.String(length=64), nullable=True),
    sa.Column('signed_off_at', sa.DateTime(), nullable=False),
    sa.Column('ftx_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['tradoc_items.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('newsletter_attachments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('newsletter_id', sa.Integer(), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('orig_name', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=120), nullable=False),
    sa.Column('size', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['newsletter_id'], ['newsletters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_newsletter_attachments_newsletter_id'), 'newsletter_attachments', ['newsletter_id'], unique=False)
    op.create_table('newsletter_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('newsletter_id', sa.Integer(), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('orig_name', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=120), nullable=False),
    sa.Column('size', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['newsletter_id'], ['newsletters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_newsletter_images_newsletter_id'), 'newsletter_images', ['newsletter_id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('link', sa.String(length=512), nullable=True),
    sa.Column('icon', sa.String(length=8), nullable=True),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_index('ix_notifications_member_read', 'notifications', ['member_id', 'read_at'], unique=False)
    op.create_table('promotion_stages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('from_rank', sa.String(length=4), nullable=True),
    sa.Column('to_rank', sa.String(length=4), nullable=False),
    sa.Column('action_type', sa.String(length=16), nullable=False),
    sa.Column('is_officer', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('target_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('staged_by', sa.String(length=64), nullable=True),
    sa.Column('staged_at', sa.DateTime(), nullable=False),
    sa.Column('finalized_by', sa.String(length=64), nullable=True),
    sa.Column('finalized_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_promotion_stages_member_id'), 'promotion_stages', ['member_id'], unique=False)
    op.create_table('rank_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('old_rank', sa.String(length=4), nullable=True),
    sa.Column('new_rank', sa.String(length=4), nullable=False),
    sa.Column('changed_by', sa.String(length=64), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('effective_date', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rank_history_member_id'), 'rank_history', ['member_id'], unique=False)
    op.create_table('s4_equipment_donations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('donor_id', sa.Integer(), nullable=False),
    sa.Column('item_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('condition', sa.String(length=50), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('photo_url', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('reviewed_by_id', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('received_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['donor_id'], ['members.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_by_id'], ['members.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_s4_equipment_donations_id'), 's4_equipment_donations', ['id'], unique=False)
    op.create_table('s4_purchase_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('requester_id', sa.Integer(), nullable=False),
    sa.Column('item_name', sa.String(length=100), nullable=False),
    sa.Column('url', sa.String(length=255), nullable=True),
    sa.Column('estimated_cost', sa.Float(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('justification', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('approved_by_id', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('denial_reason', sa.Text(), nullable=True),
    sa.Column('purchased_at', sa.DateTime(), nullable=True),
    sa.Column('received_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by_id'], ['members.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['requester_id'], ['members.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_s4_purchase_requests_id'), 's4_purchase_requests', ['id'], unique=False)
    op.create_table('separation_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=64), nullable=False),
    sa.Column('initiated_by', sa.String(length=64), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('nc_account_disabled', sa.Boolean(), nullable=False),
    sa.Column('portal_access_revoked', sa.Boolean(), nullable=False),
    sa.Column('groups_removed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shop_reporting',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shop_key', sa.String(length=8), nullable=False),
    sa.Column('reports_to_member_id', sa.Integer(), nullable=True),
    sa.Column('command_led', sa.Boolean(), nullable=False),
    sa.Column('note', sa.String(length=120), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['reports_to_member_id'], ['members.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shop_key')
    )
    op.create_table('shop_signup_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('shop_key', sa.String(length=8), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('reviewed_by', sa.String(length=64), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('review_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('training_claims',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('claim_type', sa.String(length=16), nullable=False),
    sa.Column('reference_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('doc_path', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('reviewed_by', sa.String(length=64), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('review_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('event_aar_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=16), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('event_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('doc_type', sa.String(length=16), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('visibility', sa.String(length=16), nullable=False),
    sa.Column('uploaded_by', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('event_guard_slots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('slot_number', sa.Integer(), nullable=False),
    sa.Column('slot_label', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('event_rsvps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('responded_at', sa.DateTime(), nullable=True),
    sa.Column('auto_declined', sa.Boolean(), nullable=False),
    sa.Column('guest_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('checked_in', sa.Boolean(), nullable=False),
    sa.Column('checked_in_at', sa.DateTime(), nullable=True),
    sa.Column('checked_in_by', sa.String(length=64), nullable=True),
    sa.Column('attended', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('event_schedule_blocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('day_number', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.String(length=4), nullable=False),
    sa.Column('end_time', sa.String(length=4), nullable=True),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('activity_type', sa.String(length=16), nullable=False),
    sa.Column('instructor_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['instructor_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('event_vexillations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('commander_id', sa.Integer(), nullable=True),
    sa.Column('field_status', sa.String(length=16), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['commander_id'], ['members.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'name', name='uq_vex_event_name')
    )
    op.create_table('s4_expenses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('receipt_url', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('reimbursed_at', sa.DateTime(), nullable=True),
    sa.Column('reimbursed_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reimbursed_by_id'], ['members.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_s4_expenses_id'), 's4_expenses', ['id'], unique=False)
    op.create_table('s4_inventory_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('qr_code', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('serial_number', sa.String(length=50), nullable=True),
    sa.Column('source_type', sa.String(length=20), nullable=True),
    sa.Column('source_purchase_id', sa.Integer(), nullable=True),
    sa.Column('source_donation_id', sa.Integer(), nullable=True),
    sa.Column('condition', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['source_donation_id'], ['s4_equipment_donations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_purchase_id'], ['s4_purchase_requests.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_s4_inventory_items_id'), 's4_inventory_items', ['id'], unique=False)
    op.create_index(op.f('ix_s4_inventory_items_qr_code'), 's4_inventory_items', ['qr_code'], unique=True)
    op.create_table('s4_meal_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('sat_breakfast', sa.Boolean(), nullable=True),
    sa.Column('sat_lunch', sa.Boolean(), nullable=True),
    sa.Column('sat_dinner', sa.Boolean(), nullable=True),
    sa.Column('sun_breakfast', sa.Boolean(), nullable=True),
    sa.Column('menu_notes', sa.Text(), nullable=True),
    sa.Column('assigned_to_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to_id'], ['members.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id')
    )
    op.create_index(op.f('ix_s4_meal_plans_id'), 's4_meal_plans', ['id'], unique=False)
    op.create_table('event_guests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('rsvp_id', sa.Integer(), nullable=True),
    sa.Column('sponsor_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=64), nullable=False),
    sa.Column('last_name', sa.String(length=64), nullable=False),
    sa.Column('relation', sa.String(length=16), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('waiver_ack', sa.Boolean(), nullable=False),
    sa.Column('is_walkin', sa.Boolean(), nullable=False),
    sa.Column('checked_in_at', sa.DateTime(), nullable=True),
    sa.Column('registered_by', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['rsvp_id'], ['event_rsvps.id'], ),
    sa.ForeignKeyConstraint(['sponsor_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('s4_checkouts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('checked_out_at', sa.DateTime(), nullable=True),
    sa.Column('checked_out_by_id', sa.Integer(), nullable=True),
    sa.Column('expected_return_at', sa.DateTime(), nullable=True),
    sa.Column('checked_in_at', sa.DateTime(), nullable=True),
    sa.Column('checked_in_by_id', sa.Integer(), nullable=True),
    sa.Column('return_condition', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['checked_in_by_id'], ['members.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['checked_out_by_id'], ['members.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['item_id'], ['s4_inventory_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_s4_checkouts_id'), 's4_checkouts', ['id'], unique=False)
    op.create_table('event_buddy_pairs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('member_a_id', sa.Integer(), nullable=True),
    sa.Column('member_b_id', sa.Integer(), nullable=True),
    sa.Column('guest_a_id', sa.Integer(), nullable=True),
    sa.Column('guest_b_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['guest_a_id'], ['event_guests.id'], ),
    sa.ForeignKeyConstraint(['guest_b_id'], ['event_guests.id'], ),
    sa.ForeignKeyConstraint(['member_a_id'], ['members.id'], ),
    sa.ForeignKeyConstraint(['member_b_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'member_a_id', name='uq_buddy_member_a'),
    sa.UniqueConstraint('event_id', 'member_b_id', name='uq_buddy_member_b')
    )
    op.create_table('event_guard_duty',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('slot_id', sa.Integer(), nullable=True),
    sa.Column('slot_number', sa.Integer(), nullable=False),
    sa.Column('slot_label', sa.String(length=32), nullable=True),
    sa.Column('member_id', sa.Integer(), nullable=True),
    sa.Column('guest_id', sa.Integer(), nullable=True),
    sa.Column('assigned_by', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['guest_id'], ['event_guests.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.ForeignKeyConstraint(['slot_id'], ['event_guard_slots.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'slot_number', 'member_id', name='uq_guard_event_slot_member')
    )
    op.create_table('event_vexillation_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('vexillation_id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=True),
    sa.Column('guest_id', sa.Integer(), nullable=True),
    sa.Column('assigned_by', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['guest_id'], ['event_guests.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.ForeignKeyConstraint(['vexillation_id'], ['event_vexillations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'member_id', name='uq_vex_assign_member')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event_vexillation_assignments')
    op.drop_table('event_guard_duty')
    op.drop_table('event_buddy_pairs')
    op.drop_index(op.f('ix_s4_checkouts_id'), table_name='s4_checkouts')
    op.drop_table('s4_checkouts')
    op.drop_table('event_guests')
    op.drop_index(op.f('ix_s4_meal_plans_id'), table_name='s4_meal_plans')
    op.drop_table('s4_meal_plans')
    op.drop_index(op.f('ix_s4_inventory_items_qr_code'), table_name='s4_inventory_items')
    op.drop_index(op.f('ix_s4_inventory_items_id'), table_name='s4_inventory_items')
    op.drop_table('s4_inventory_items')
    op.drop_index(op.f('ix_s4_expenses_id'), table_name='s4_expenses')
    op.drop_table('s4_expenses')
    op.drop_table('event_vexillations')
    op.drop_table('event_schedule_blocks')
    op.drop_table('event_rsvps')
    op.drop_table('event_guard_slots')
    op.drop_table('event_documents')
    op.drop_table('event_aar_items')
    op.drop_table('training_claims')
    op.drop_table('shop_signup_requests')
    op.drop_table('shop_reporting')
    op.drop_table('separation_log')
    op.drop_index(op.f('ix_s4_purchase_requests_id'), table_name='s4_purchase_requests')
    op.drop_table('s4_purchase_requests')
    op.drop_index(op.f('ix_s4_equipment_donations_id'), table_name='s4_equipment_donations')
    op.drop_table('s4_equipment_donations')
    op.drop_index(op.f('ix_rank_history_member_id'), table_name='rank_history')
    op.drop_table('rank_history')
    op.drop_index(op.f('ix_promotion_stages_member_id'), table_name='promotion_stages')
    op.drop_table('promotion_stages')
    op.drop_index('ix_notifications_member_read', table_name='notifications')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_newsletter_images_newsletter_id'), table_name='newsletter_images')
    op.drop_table('newsletter_images')
    op.drop_index(op.f('ix_newsletter_attachments_newsletter_id'), table_name='newsletter_attachments')
    op.drop_table('newsletter_attachments')
    op.drop_table('member_tradoc')
    op.drop_index(op.f('ix_member_ribbons_ribbon_code'), table_name='member_ribbons')
    op.drop_index(op.f('ix_member_ribbons_member_id'), table_name='member_ribbons')
    op.drop_table('member_ribbons')
    op.drop_table('member_certifications')
    op.drop_table('member_awards')
    op.drop_index(op.f('ix_events_series_id'), table_name='events')
    op.drop_table('events')
    op.drop_table('election_voter_roll')
    op.drop_table('election_nominations')
    op.drop_table('election_nomination_receipts')
    op.drop_table('election_ballots')
    op.drop_table('document_signatures')
    op.drop_index(op.f('ix_conduct_violations_member_id'), table_name='conduct_violations')
    op.drop_table('conduct_violations')
    op.drop_table('webhook_events')
    op.drop_table('tradoc_tiers')
    op.drop_table('tradoc_items')
    op.drop_table('tradoc_blocks')
    op.drop_table('threat_levels')
    op.drop_table('teams')
    op.drop_table('shops')
    op.drop_index(op.f('ix_ribbon_catalog_code'), table_name='ribbon_catalog')
    op.drop_table('ribbon_catalog')
    op.drop_table('recruiters')
    op.drop_table('ranks')
    op.drop_index(op.f('ix_newsletters_status'), table_name='newsletters')
    op.drop_index(op.f('ix_newsletters_scheduled_at'), table_name='newsletters')
    op.drop_table('newsletters')
    op.drop_index(op.f('ix_newsletter_section_templates_key'), table_name='newsletter_section_templates')
    op.drop_table('newsletter_section_templates')
    op.drop_table('nc_rooms')
    op.drop_index(op.f('ix_members_nc_username'), table_name='members')
    op.drop_table('members')
    op.drop_index(op.f('ix_member_weapons_qual_member_id'), table_name='member_weapons_qual')
    op.drop_index(op.f('ix_member_weapons_qual_event_id'), table_name='member_weapons_qual')
    op.drop_table('member_weapons_qual')
    op.drop_table('member_statuses')
    op.drop_table('library_document')
    op.drop_table('library_categories')
    op.drop_table('event_categories')
    op.drop_table('elections')
    op.drop_table('certifications')
    op.drop_table('app_settings')
    # ### end Alembic commands ###
