"""reconcile prod schema drift to models (post-squash)

Revision ID: 0002_reconcile
Revises: 0001_baseline
Create Date: 2026-07-27

WHY THIS EXISTS
---------------
0001_baseline was autogenerated from the current models, so a from-scratch
`alembic upgrade head` produces the exact model schema. But the LIVE prod DB
predates the squash: its schema is the historical create_all() + 46 migrations
result, which has minor cosmetic drift vs the models (a few nullable flags, two
legacy index names, some redundant indexes / a redundant unique constraint).

This revision reconciles that drift so `alembic check` is clean on BOTH a
from-scratch DB and prod. Because the two starting points differ, every op here
is written to be IDEMPOTENT:
  * `SET NOT NULL` is a natural no-op when the column is already NOT NULL
    (from-scratch baseline already emits these columns NOT NULL).
  * index drops use `DROP INDEX IF EXISTS`.
  * the conduct_violations index rename only fires when the old name exists.
  * the redundant unique constraint drop is guarded on its existence.

Data preconditions verified on prod before writing this (2026-07-27):
  * all NOT NULL target columns had 0 NULL rows (teams.updated_at had 6 NULLs;
    those were backfilled to now() first).
  * document_signatures.ip_address is NOT shrunk — prod stores IPv6 +
    Cloudflare-forwarded chains up to ~56 chars, so the model was widened to
    String(255) to match prod instead.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

revision: str = "0002_reconcile"
down_revision: Union[str, None] = "0001_baseline"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# Columns that must end up NOT NULL. SET NOT NULL is idempotent, so this is safe
# whether the starting schema had them nullable (prod) or already NOT NULL
# (from-scratch baseline).
_NOT_NULL = [
    ("conduct_violations", "created_at"),
    ("library_document", "uploaded_at"),
    ("member_weapons_qual", "recorded_at"),
    ("newsletter_attachments", "created_at"),
    ("newsletter_images", "created_at"),
    ("newsletter_section_templates", "created_at"),
    ("newsletter_section_templates", "updated_at"),
    ("newsletters", "created_at"),
    ("newsletters", "updated_at"),
    ("promotion_stages", "staged_at"),
    ("shop_reporting", "updated_at"),
    ("shop_signup_requests", "created_at"),
    ("teams", "updated_at"),
]

# Redundant indexes present on prod but not modeled. IF EXISTS makes the drop a
# no-op on a from-scratch DB where they were never created.
_DROP_INDEXES = [
    "ix_library_document_category",
    "ix_shop_signup_requests_status",
    "ix_webhook_events_txn",
]


def upgrade() -> None:
    conn = op.get_bind()

    for table, col in _NOT_NULL:
        op.alter_column(table, col, nullable=False)

    # Legacy index name -> modeled name (only when the old one still exists).
    op.execute("DROP INDEX IF EXISTS ix_conduct_violations_member")
    conn.execute(
        sa.text(
            "CREATE INDEX IF NOT EXISTS ix_conduct_violations_member_id "
            "ON conduct_violations (member_id)"
        )
    )

    for idx in _DROP_INDEXES:
        op.execute(f"DROP INDEX IF EXISTS {idx}")

    # Redundant unique constraint on newsletter_section_templates.key
    # (the column is already modeled unique via a plain unique=True index path);
    # drop the named constraint only if present.
    op.execute(
        "ALTER TABLE newsletter_section_templates "
        "DROP CONSTRAINT IF EXISTS newsletter_section_templates_key_key"
    )


def downgrade() -> None:
    # Best-effort reversal. Recreate the dropped objects and relax the columns.
    op.execute(
        "CREATE INDEX IF NOT EXISTS ix_webhook_events_txn "
        "ON webhook_events (transaction_id)"
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS ix_shop_signup_requests_status "
        "ON shop_signup_requests (status)"
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS ix_library_document_category "
        "ON library_document (category)"
    )
    op.execute(
        "CREATE UNIQUE INDEX IF NOT EXISTS newsletter_section_templates_key_key "
        "ON newsletter_section_templates (key)"
    )
    op.execute("DROP INDEX IF EXISTS ix_conduct_violations_member_id")
    op.execute(
        "CREATE INDEX IF NOT EXISTS ix_conduct_violations_member "
        "ON conduct_violations (member_id)"
    )
    for table, col in _NOT_NULL:
        op.alter_column(table, col, nullable=True)
