"""Initial schema - members table

Revision ID: 06f355945bf5
Revises: 
Create Date: 2026-03-04 23:59:22.519941
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '06f355945bf5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nc_username', sa.String(length=64), nullable=False),
    sa.Column('first_name', sa.String(length=64), nullable=False),
    sa.Column('last_name', sa.String(length=64), nullable=False),
    sa.Column('callsign', sa.String(length=32), nullable=True),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('rank_grade', sa.String(length=4), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('team', sa.String(length=32), nullable=True),
    sa.Column('company', sa.String(length=64), nullable=False),
    sa.Column('primary_billet', sa.String(length=64), nullable=True),
    sa.Column('secondary_billet', sa.String(length=64), nullable=True),
    sa.Column('join_date', sa.Date(), nullable=True),
    sa.Column('patch_date', sa.Date(), nullable=True),
    sa.Column('separation_date', sa.Date(), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('city', sa.String(length=64), nullable=True),
    sa.Column('state', sa.String(length=2), nullable=True),
    sa.Column('zip_code', sa.String(length=10), nullable=True),
    sa.Column('ham_callsign', sa.String(length=10), nullable=True),
    sa.Column('ham_license_class', sa.String(length=16), nullable=True),
    sa.Column('is_veteran', sa.Boolean(), nullable=False),
    sa.Column('mos', sa.String(length=16), nullable=True),
    sa.Column('has_ltc', sa.Boolean(), nullable=False),
    sa.Column('portal_roles', sa.Text(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_members_nc_username'), 'members', ['nc_username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_members_nc_username'), table_name='members')
    op.drop_table('members')
    # ### end Alembic commands ###
