"""Add S4 logistics models

Revision ID: e41bcdde1415
Revises: k2l3m4n5o6p7
Create Date: 2026-04-17 19:51:02.501660
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'e41bcdde1415'
down_revision: Union[str, None] = 'k2l3m4n5o6p7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('s4_equipment_donations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('donor_id', sa.Integer(), nullable=False),
    sa.Column('item_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('condition', sa.String(length=50), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('photo_url', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('reviewed_by_id', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('received_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['donor_id'], ['members.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_by_id'], ['members.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_s4_equipment_donations_id'), 's4_equipment_donations', ['id'], unique=False)
    op.create_table('s4_purchase_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('requester_id', sa.Integer(), nullable=False),
    sa.Column('item_name', sa.String(length=100), nullable=False),
    sa.Column('url', sa.String(length=255), nullable=True),
    sa.Column('estimated_cost', sa.Float(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('justification', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('approved_by_id', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('denial_reason', sa.Text(), nullable=True),
    sa.Column('purchased_at', sa.DateTime(), nullable=True),
    sa.Column('received_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by_id'], ['members.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['requester_id'], ['members.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_s4_purchase_requests_id'), 's4_purchase_requests', ['id'], unique=False)
    op.create_table('s4_expenses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('receipt_url', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('reimbursed_at', sa.DateTime(), nullable=True),
    sa.Column('reimbursed_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reimbursed_by_id'], ['members.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_s4_expenses_id'), 's4_expenses', ['id'], unique=False)
    op.create_table('s4_inventory_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('qr_code', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('serial_number', sa.String(length=50), nullable=True),
    sa.Column('source_type', sa.String(length=20), nullable=True),
    sa.Column('source_purchase_id', sa.Integer(), nullable=True),
    sa.Column('source_donation_id', sa.Integer(), nullable=True),
    sa.Column('condition', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['source_donation_id'], ['s4_equipment_donations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_purchase_id'], ['s4_purchase_requests.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_s4_inventory_items_id'), 's4_inventory_items', ['id'], unique=False)
    op.create_index(op.f('ix_s4_inventory_items_qr_code'), 's4_inventory_items', ['qr_code'], unique=True)
    op.create_table('s4_meal_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('sat_breakfast', sa.Boolean(), nullable=True),
    sa.Column('sat_lunch', sa.Boolean(), nullable=True),
    sa.Column('sat_dinner', sa.Boolean(), nullable=True),
    sa.Column('sun_breakfast', sa.Boolean(), nullable=True),
    sa.Column('menu_notes', sa.Text(), nullable=True),
    sa.Column('assigned_to_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to_id'], ['members.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id')
    )
    op.create_index(op.f('ix_s4_meal_plans_id'), 's4_meal_plans', ['id'], unique=False)
    op.create_table('s4_checkouts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('checked_out_at', sa.DateTime(), nullable=True),
    sa.Column('checked_out_by_id', sa.Integer(), nullable=True),
    sa.Column('expected_return_at', sa.DateTime(), nullable=True),
    sa.Column('checked_in_at', sa.DateTime(), nullable=True),
    sa.Column('checked_in_by_id', sa.Integer(), nullable=True),
    sa.Column('return_condition', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['checked_in_by_id'], ['members.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['checked_out_by_id'], ['members.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['item_id'], ['s4_inventory_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_s4_checkouts_id'), 's4_checkouts', ['id'], unique=False)
    op.drop_index('ix_notifications_id', table_name='notifications')
    op.drop_index('ix_notifications_member_read', table_name='notifications')
    op.drop_table('notifications')
    op.alter_column('document_signatures', 'member_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('document_signatures', 'document_version',
               existing_type=sa.VARCHAR(length=16),
               nullable=False,
               existing_server_default=sa.text("'1.0'::character varying"))
    op.alter_column('document_signatures', 'signed_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('document_signatures', 'ip_address',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.drop_index('idx_document_signatures_member', table_name='document_signatures')
    op.drop_index('ix_election_ballots_election', table_name='election_ballots')
    op.drop_index('ix_election_ballots_nominee', table_name='election_ballots')
    op.drop_index('ix_election_nomination_receipts_election', table_name='election_nomination_receipts')
    op.drop_index('ix_election_nominations_election', table_name='election_nominations')
    op.drop_index('ix_election_voter_roll_election', table_name='election_voter_roll')
    op.drop_index('ix_elections_phase', table_name='elections')
    op.alter_column('event_aar_items', 'ordinal',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('event_aar_items', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_aar_items_event', table_name='event_aar_items')
    op.drop_index('ix_event_buddy_pairs_event_id', table_name='event_buddy_pairs')
    op.drop_index('idx_event_docs_event', table_name='event_documents')
    op.drop_constraint('event_documents_event_id_fkey', 'event_documents', type_='foreignkey')
    op.create_foreign_key(None, 'event_documents', 'events', ['event_id'], ['id'])
    op.drop_index('ix_event_guard_duty_event_id', table_name='event_guard_duty')
    op.drop_index('ix_event_guard_slots_event_id', table_name='event_guard_slots')
    op.drop_index('ix_event_guests_event_id', table_name='event_guests')
    op.drop_constraint('event_rsvps_event_id_member_id_key', 'event_rsvps', type_='unique')
    op.drop_index('idx_event_rsvps_event', table_name='event_rsvps')
    op.drop_index('idx_event_rsvps_member', table_name='event_rsvps')
    op.drop_index('idx_event_rsvps_status', table_name='event_rsvps')
    op.drop_constraint('event_rsvps_event_id_fkey', 'event_rsvps', type_='foreignkey')
    op.create_foreign_key(None, 'event_rsvps', 'events', ['event_id'], ['id'])
    op.drop_index('ix_schedule_blocks_event_id', table_name='event_schedule_blocks')
    op.drop_index('ix_event_vex_assign_event_id', table_name='event_vexillation_assignments')
    op.drop_index('ix_event_vex_assign_vex_id', table_name='event_vexillation_assignments')
    op.drop_index('ix_event_vexillations_event_id', table_name='event_vexillations')
    op.drop_index('idx_events_date_start', table_name='events')
    op.drop_index('idx_events_status', table_name='events')
    op.drop_column('events', 'warno_released_at')
    op.drop_column('events', 'opord_released_at')
    op.alter_column('member_awards', 'awarded_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('idx_member_awards_member', table_name='member_awards')
    op.drop_index('idx_member_certifications_member', table_name='member_certifications')
    op.drop_index('idx_member_tradoc_member', table_name='member_tradoc')
    op.alter_column('members', 'ftx_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('members', 'is_founder',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('members', 'is_hq',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('members', 'app_fee_amount',
               existing_type=sa.NUMERIC(precision=6, scale=2),
               type_=sa.Float(),
               existing_nullable=True,
               existing_server_default=sa.text('50.00'))
    op.drop_index('idx_members_status', table_name='members')
    op.drop_index('idx_members_team', table_name='members')
    op.alter_column('recruiters', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('recruiters', 'current_load',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('recruiters', 'max_load',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('5'))
    op.alter_column('recruiters', 'total_recruited',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('recruiters', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('separation_log', 'member_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('separation_log', 'nc_account_disabled',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('separation_log', 'portal_access_revoked',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('separation_log', 'groups_removed',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('separation_log', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('idx_separation_log_member', table_name='separation_log')
    op.alter_column('threat_levels', 'set_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('unique_tradoc_name', 'tradoc_items', type_='unique')
    op.drop_index('idx_training_claims_member', table_name='training_claims')
    op.drop_index('idx_training_claims_status', table_name='training_claims')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_training_claims_status', 'training_claims', ['status'], unique=False)
    op.create_index('idx_training_claims_member', 'training_claims', ['member_id'], unique=False)
    op.create_unique_constraint('unique_tradoc_name', 'tradoc_items', ['name'], postgresql_nulls_not_distinct=False)
    op.alter_column('threat_levels', 'set_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index('idx_separation_log_member', 'separation_log', ['member_id'], unique=False)
    op.alter_column('separation_log', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('separation_log', 'groups_removed',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('separation_log', 'portal_access_revoked',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('separation_log', 'nc_account_disabled',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('separation_log', 'member_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('recruiters', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('recruiters', 'total_recruited',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('recruiters', 'max_load',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('5'))
    op.alter_column('recruiters', 'current_load',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('recruiters', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.create_index('idx_members_team', 'members', ['team'], unique=False)
    op.create_index('idx_members_status', 'members', ['status'], unique=False)
    op.alter_column('members', 'app_fee_amount',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=6, scale=2),
               existing_nullable=True,
               existing_server_default=sa.text('50.00'))
    op.alter_column('members', 'is_hq',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('members', 'is_founder',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('members', 'ftx_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.create_index('idx_member_tradoc_member', 'member_tradoc', ['member_id'], unique=False)
    op.create_index('idx_member_certifications_member', 'member_certifications', ['member_id'], unique=False)
    op.create_index('idx_member_awards_member', 'member_awards', ['member_id'], unique=False)
    op.alter_column('member_awards', 'awarded_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.add_column('events', sa.Column('opord_released_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('events', sa.Column('warno_released_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.create_index('idx_events_status', 'events', ['status'], unique=False)
    op.create_index('idx_events_date_start', 'events', ['date_start'], unique=False)
    op.create_index('ix_event_vexillations_event_id', 'event_vexillations', ['event_id'], unique=False)
    op.create_index('ix_event_vex_assign_vex_id', 'event_vexillation_assignments', ['vexillation_id'], unique=False)
    op.create_index('ix_event_vex_assign_event_id', 'event_vexillation_assignments', ['event_id'], unique=False)
    op.create_index('ix_schedule_blocks_event_id', 'event_schedule_blocks', ['event_id'], unique=False)
    op.drop_constraint(None, 'event_rsvps', type_='foreignkey')
    op.create_foreign_key('event_rsvps_event_id_fkey', 'event_rsvps', 'events', ['event_id'], ['id'], ondelete='CASCADE')
    op.create_index('idx_event_rsvps_status', 'event_rsvps', ['status'], unique=False)
    op.create_index('idx_event_rsvps_member', 'event_rsvps', ['member_id'], unique=False)
    op.create_index('idx_event_rsvps_event', 'event_rsvps', ['event_id'], unique=False)
    op.create_unique_constraint('event_rsvps_event_id_member_id_key', 'event_rsvps', ['event_id', 'member_id'], postgresql_nulls_not_distinct=False)
    op.create_index('ix_event_guests_event_id', 'event_guests', ['event_id'], unique=False)
    op.create_index('ix_event_guard_slots_event_id', 'event_guard_slots', ['event_id'], unique=False)
    op.create_index('ix_event_guard_duty_event_id', 'event_guard_duty', ['event_id'], unique=False)
    op.drop_constraint(None, 'event_documents', type_='foreignkey')
    op.create_foreign_key('event_documents_event_id_fkey', 'event_documents', 'events', ['event_id'], ['id'], ondelete='CASCADE')
    op.create_index('idx_event_docs_event', 'event_documents', ['event_id'], unique=False)
    op.create_index('ix_event_buddy_pairs_event_id', 'event_buddy_pairs', ['event_id'], unique=False)
    op.create_index('ix_aar_items_event', 'event_aar_items', ['event_id'], unique=False)
    op.alter_column('event_aar_items', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('event_aar_items', 'ordinal',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index('ix_elections_phase', 'elections', ['phase'], unique=False)
    op.create_index('ix_election_voter_roll_election', 'election_voter_roll', ['election_id'], unique=False)
    op.create_index('ix_election_nominations_election', 'election_nominations', ['election_id'], unique=False)
    op.create_index('ix_election_nomination_receipts_election', 'election_nomination_receipts', ['election_id'], unique=False)
    op.create_index('ix_election_ballots_nominee', 'election_ballots', ['nominee_id'], unique=False)
    op.create_index('ix_election_ballots_election', 'election_ballots', ['election_id'], unique=False)
    op.create_index('idx_document_signatures_member', 'document_signatures', ['member_id'], unique=False)
    op.alter_column('document_signatures', 'ip_address',
               existing_type=sa.String(length=45),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('document_signatures', 'signed_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('document_signatures', 'document_version',
               existing_type=sa.VARCHAR(length=16),
               nullable=True,
               existing_server_default=sa.text("'1.0'::character varying"))
    op.alter_column('document_signatures', 'member_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_table('notifications',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('member_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('category', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=256), autoincrement=False, nullable=False),
    sa.Column('body', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('link', sa.VARCHAR(length=512), autoincrement=False, nullable=True),
    sa.Column('icon', sa.VARCHAR(length=8), autoincrement=False, nullable=True),
    sa.Column('read_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], name='notifications_member_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='notifications_pkey')
    )
    op.create_index('ix_notifications_member_read', 'notifications', ['member_id', 'read_at'], unique=False)
    op.create_index('ix_notifications_id', 'notifications', ['id'], unique=False)
    op.drop_index(op.f('ix_s4_checkouts_id'), table_name='s4_checkouts')
    op.drop_table('s4_checkouts')
    op.drop_index(op.f('ix_s4_meal_plans_id'), table_name='s4_meal_plans')
    op.drop_table('s4_meal_plans')
    op.drop_index(op.f('ix_s4_inventory_items_qr_code'), table_name='s4_inventory_items')
    op.drop_index(op.f('ix_s4_inventory_items_id'), table_name='s4_inventory_items')
    op.drop_table('s4_inventory_items')
    op.drop_index(op.f('ix_s4_expenses_id'), table_name='s4_expenses')
    op.drop_table('s4_expenses')
    op.drop_index(op.f('ix_s4_purchase_requests_id'), table_name='s4_purchase_requests')
    op.drop_table('s4_purchase_requests')
    op.drop_index(op.f('ix_s4_equipment_donations_id'), table_name='s4_equipment_donations')
    op.drop_table('s4_equipment_donations')
    # ### end Alembic commands ###
