"""Add Code of Conduct and Bylaws signatures

Revision ID: g8h9i0j1k2l3
Revises: g7h8i9j0k1l2
Create Date: 2026-04-01 11:25:00.000000

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'g8h9i0j1k2l3'
down_revision = 'g7h8i9j0k1l2'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('members', sa.Column('code_of_conduct_signed_at', sa.DateTime(), nullable=True))
    op.add_column('members', sa.Column('code_of_conduct_ip_address', sa.String(length=255), nullable=True))
    op.add_column('members', sa.Column('bylaws_signed_at', sa.DateTime(), nullable=True))
    op.add_column('members', sa.Column('bylaws_ip_address', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('members', 'bylaws_ip_address')
    op.drop_column('members', 'bylaws_signed_at')
    op.drop_column('members', 'code_of_conduct_ip_address')
    op.drop_column('members', 'code_of_conduct_signed_at')
    # ### end Alembic commands ###
